<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Bogus" Version="35.6.5" />
    <PackageVersion Include="Rocks" Version="10.2.0" />
    <PackageVersion Include="TUnit" Version="1.63.25" />
  </ItemGroup>
</Project>
