namespace Gg.Contracts;

/// <summary>
/// The complete vocabulary: every event and fact type that may cross the
/// boundary between a customer's environment and the control plane. A type
/// missing from this list fails the build — silently absent is not a state
/// this manifest allows.
/// </summary>
public static class Vocabulary
{
    public static IReadOnlyList<Type> Types { get; } =
    [
        typeof(ProtocolHello),
        typeof(DeviceAuthorizationRequest),
        typeof(DeviceAuthorizationStarted),
        typeof(DeviceTokenRequest),
        typeof(SessionIssued),
        typeof(WhoAmI),
        typeof(TenantNotice),
        typeof(RunnerRegistrationRequest),
        typeof(RunnerRegistered),
        typeof(RunnerHeartbeat),
        typeof(HeartbeatAccepted),
        typeof(LeaseClaimRequest),
        typeof(LeaseRepoRef),
        typeof(LeaseLoop),
        typeof(LeaseGranted),
        typeof(LeaseRenewalRequest),
        typeof(LeaseRenewed),
        typeof(LeaseReleaseRequest),
        typeof(LeaseReleased),
        typeof(FlightIntent),
        typeof(FlightLaunchRequest),
        typeof(FlightLaunched),
        typeof(FlightSummary),
        typeof(FlightList),
        typeof(FlightLogEntry),
        typeof(FlightLog),
        typeof(RunnerSummary),
        typeof(RunnerList),
        typeof(TelemetryDisclosure),
        typeof(CredentialReference),
        typeof(CredentialRegistrationRequest),
        typeof(CredentialRegistered),
        typeof(CredentialSummary),
        typeof(CredentialList),
        typeof(CredentialRemoved),
        typeof(CredentialResolutionFailure),
        typeof(LockHash),
        typeof(ToolVersion),
        typeof(EnvironmentIdentity),
        typeof(SourceProvenance),
        typeof(FactEnvelope),
        typeof(FactBatch),
        typeof(FactRejection),
        typeof(FactBatchAccepted),
        typeof(ClassificationRule),
        typeof(ChangedPath),
        typeof(DirectoryChange),
        typeof(LanguageChange),
        typeof(ChangeManifest),
        typeof(LoopOutcome),
        typeof(DestinationLanded),
        typeof(LoopDigest),
        typeof(HumanAccount),
        typeof(FlightAttribution),
        typeof(DestinationPushed),
        typeof(GateList),
        typeof(PendingGate),
        typeof(BranchPush),
        typeof(GateList),
        typeof(PendingGate),
        typeof(BranchPush),
        typeof(ObligationAttribution),
        typeof(TakeoverRecord),
        typeof(TakeoverReturn),
        typeof(DigestError),
        typeof(DestinationAdmission),
        typeof(ArtifactReference),
        typeof(ContextBinding),
        typeof(Obligation),
        typeof(LoopBudget),
        typeof(Loop),
        typeof(Destination),
        typeof(Envelope),
        typeof(EnvelopeState),
        typeof(EnvelopeApplied),
    ];
}
